/**
 * Created by ionagamed on 8/25/16.
 */

const translationMapping = {
    'gelatinous_octahedron': 'Желатиновый Октаэдр',
    'ghoulfiends': 'Мадемонуазели',
    'harpies': 'Гарпистки',
    'hippogriff': 'Гиппогриф',
    'insurance_salesman': 'Страховой Агент',
    '3872_orcs': '3872 орка',
    'amazon': 'Амазонка',
    'bigfoot': 'Бигфут',
    'bullrog': 'Бульрог',
    'crabs': 'Типа Вошки',
    'curse_lose_small_item': 'Невелика Потеря',
    'curse_lose_armor': 'Теряешь Надетый Броник',
    'curse_lose_footgear': 'Теряешь Надетую Обувку',
    'curse_lose_headgear': 'Теряешь Надетый Головняк',
    'wizard': 'Волшебник',
    'curse_change_class': 'Смена Класса',
    'curse_change_race': 'Смена Расы',
    'curse_change_sex': 'Смена Пола',
    'curse_chicken': 'Курица На Башне',
    'halfling': 'Халфлинг',
    'thief': 'Вор',
    'half-breed': 'Полукровка',
    'help_me_out_here': 'Помоги Себе Сам!',
    'illusion': 'Иллюзия',
    'mate': 'Гадкая Парочка',
    'out_to_lunch': 'Ушёл На Обед',
    'squidzilla': 'Кальмадзилла',
    'stoned_golem': 'Обдолбанный Голем',
    'tongue_demon': 'Языческий Демон',
    'undead_horse': 'Андедный Коник',
    'horror': 'Невыразимо Жуткий Неописуемый Ужас',
    'ancient': 'Древний',
    'baby': 'Детёныш',
    'enraged': 'Психованный',
    'humongous': 'Амбал',
    'intelligent': 'Мозговитый',
    'maul_rat': 'Молотая Крысотка',
    'mr_bones': 'Г-н Кости',
    'net_troll': 'Форумный Тролль',
    'pit_bull': 'Питбуль',
    'platycore': 'Утикора',
    'cleric': 'Клирик',
    'dwarf': 'Дварф',
    'plutonium_dragon': 'Плутониевый Дракон',
    'potted_plant': 'Трава В Горшке',
    'pukachu': 'Рыгачу',
    'shrieking_geek': 'Вопящий Задрот',
    'snails_on_speed': 'Ускоренные Улитки',
    'elf': 'Эльф',
    'king_tut': 'Король Тут',
    'lame_goblin': 'Увечный Гоблин',
    'large_angry_chicken': 'Здоровенная Бешенная Цыпа',
    'lawyers': 'Адвокат',
    'leperchaun': 'Лепрокон',
    'drooling_slime': 'Сочащаяся Слизь',
    'face_sucker': 'Лицесос',
    'floating_nose': 'Сопливый Нос',
    'flying_frogs': 'Летучие Лягушки',
    'gazebo': 'Газебо',
    'curse_lose_two_cards': 'Теряешь 2 Карты',
    'curse_lose_class': 'Теряешь Класс',
    'curse_lose_race': 'Теряешь Расу',
    'curse_malign_mirror': 'Кривящее Зеркало',
    'truly_obnoxious_curse': 'В Конец Мерзкое Проклятие',
    'curse_duck_of_doom': 'Утка Обречённости',
    'curse_income_tax': 'Налоги',
    'curse_lose_big_item': 'Большая Потеря',
    'curse_lose_level': 'Теряешь 1 Уровень!',
    'warrior': 'Воин',
    'super_munchkin': 'Суперманчкин',
    'wandering_monster': 'Бродячая Тварь',
    'wannabe_vampire': 'Закос Под Вампира',
    'wight_brothers': 'Бледные Братья',
    'cheat': 'Чит!',
    'divine_intervention': 'Божественное Вмешательство',
    
    'male': 'мужской',
    'female': 'женский',
    
    'monster': 'монстр',
    'curse': 'проклятие',
    '1-handed': 'одноручное',
    '2-handed': 'двуручное',
    'armor': 'броник',
    'headgear': 'головняк',
    'footgear': 'обувка',
    'modifier': 'модификатор',
    
    'magic_lamp': 'Волшебная Лампа',
    'pollymorph_potion': 'Зелье Попуморфа',
    'transferral_potion': 'Зелье Стрелочника',
    'wand_of_dowsing': 'Штырь Лозоходца',
    'wishing_ring': 'Хотельное Кольцо',
    'spiky_knees': 'Острые Коленки',
    'staff_of_napalm': 'Посох Напалма',
    'stepladder': 'Боевая Стремянка',
    'swiss_army_polearm': 'Швейцарская Армейская Алебарда',
    'doppleganger': 'Дупельгангер',
    'flaming_armor': 'Палёные Доспехи',
    'gentlemans_club': 'Дуб Джельтенменов',
    'hammer_of_kneecapping': 'Коленеотбойный Молоточек',
    'helm of courage': 'Шлем Бесстрашия',
    'horny_helmet': 'Шлем-Рогач',
    'bad-ass_bandanna': 'Сорвиголовная Бандана',
    'boots_of_butt-kicking': 'Башмаки Могучего Пендаля',
    'bow_with_ribbons': 'Лук с Ленточками',
    'broad_sword': 'Меч Широты Взглядов',
    'buckler_of_swashing': 'Пафосный Баклер',
    'cotion_of_ponfusion': 'Пелье Зутаницы',
    'acid_potion': 'Радиоактивно-Электрокислотное Зелье',
    'flaming_poison_potion': 'Зелье Пламенной Отравы',
    'freezing_explosive_potion': 'Замораживающее Взрывное Зелье',
    'magic_missile': 'Магическая Ракета',
    'pantyhose_of_giant_strength': 'Колготки Великанской Силы',
    'pointy_hat_of_power': 'Остроконечная Шляпа Могущества',
    'rapier_of_unfairness': 'Рапира Такнечестности',
    'rat_on_a_stick': 'Крыса на палочке',
    'really_impressive_title': 'Реально Конкрктный Титул',
    '1000_gold': '1000 Голдов',
    'boil_an_anthill': 'Кипяток в Муравейнике',
    'bribe_gm_with_food': 'Прикорми Мастера',
    'convenient_addition_error': 'Выгодная ошибка при сложении',
    'invoke_obscure_rules': 'Используй непонятное правило',
    'boots_of_running_really_fast': 'Башмаки реально быстрого бега',
    'hireling': 'Наёмничек',
    'hoard': 'Ура, Клад!',
    'kneepads_of_allure': 'Наколенники Развода',
    'flask_of_glue': 'Тюбик Клея',
    'friendship_potion': 'Зелье Дружбы',
    'instant_wall': 'Стенка-Встанька',
    'invisibility_potion': 'Зелье Невидимости',
    'loaded_die_1': 'Читерский кубик',
    'huge_rock': 'Огромная Каменюга',
    'leather_armor': 'Кожанный Прикид',
    'sandwich': 'Сэнвич запоздалого прозрения с сыром и селёдкой',
    'mace_of_sharpiness': 'Булава остроконечности',
    'mithril_armor': 'Мифрильный доспех',
    'chainsaw': 'Бензопила крававого расчленения',
    'cheese_grater_of_piece': 'Тёрка умиротвотения',
    'cloak_of_obscurity': 'Плащ замутнения',
    'dagger_of_treachery': 'Кинжал измены',
    'eleven-foot_pole': 'Одиннадцатифутовый кий',
    'nasty-tasting_sports_drink': 'Питьё противно-спортивное',
    'potion_of_halitosis': 'Зелье ротовой воен',
    'potion_of_idiotic_bravery': 'Зелье идиотской храбрости',
    'pretty_balloons': 'Клёвые шарики',
    'sleep_potion': 'Снотворное зелье',
    'shield_of_ubiquity': 'Совсесторонний щит',
    'short_wide_armor': 'Доспехи Поперёк-Себя-Шире',
    'singing_and_dancing_sword': 'Меч песни и пляски',
    'slimy_armor': 'Склизистая оболочка',
    'sneaky_bastard_sword': 'Меч коварного бастарда',
    'kill_the_hireling': 'Рассчитайся с наёмником',
    'mutilate_the_bodies': 'Поглумились над телами врагов',
    'potion_of_general_studliness': 'Зелье Крутизны',
    'whine_at_the_gm': 'Разжалоби мастера',
    'yuppie_water': 'Яппиток',
    'yuppie_water_helper': 'Яппиток',
    'go_up_a_level': 'Получи уровень',
    'steal_a_level': 'Укради уровень',
    'tuba_of_charm': 'Чарующая дуда',
    'sandals_of_protection': 'Сандалеты-Протекторы',
    'q-dice': 'Q-Кубик',

    'Not treasure': 'Продать можно только сокровище',
    'Not owner': 'Начать игру может только первый игрок стола',
    'Not dead': 'Воскреснуть можно только если ты мертв',
    'Not playing': 'Воскреситься можно только если ты играешь',
    'Can\'t escape: winning': 'Нельзя смыться, если ты выигрываешь',
    'Fight is not yours | escape': 'Нельзя инициировать смывку из не своего боя',
    'Nice try': 'Хорошая попытка',
    'Not your turn | sell': 'Нельзя продавать шмотки не в свой ход',
    'Already kicked': 'Вы уже пнули дверь',
    'Kicking required': 'Еще не бил дверь',
    'Not your turn | turn': 'Нельзя закончить не свой ход',
    'Fight | turn': 'Нельзя закончить ход, если идет бой',
    'Too many cards': 'Слишком много карт',
    'Fight is not yours | win': 'Нельзя выиграть не свой бой',
    'Not your turn | wield': 'Нельзя одевать шмотки не в свой ход',
    'Fight | wield': 'Нельзя одевать шмотки во время боя',
    'Fight | unwield': 'Нельзя снимать шмотки во время боя',
    'Can\'t be used': 'Нельзя использовать',
    'Can\'t be cast': 'Нельзя кастануть',
    'Too many helpers': 'Итак уже много дерутся',
    'Fight | offer': 'Нельзя отдавать во время боя',
    'Not your turn | offer': 'Нельзя отдавать не в свой ход',
    'Not treasure | offer': 'Нельзя отдавать не сокровища',
    'Cannot be wielded right now': 'Не может быть одето прямо сейчас'
};

export default function (x) {
    if (!x) return x;
    if (x.substring(x.length - 2, x.length - 1) == '_') {
        x = x.substring(0, x.length - 2);
    }
    if (translationMapping.hasOwnProperty(x)) {
        return translationMapping[x];
    } else {
        return x;
    }
}
